/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Windows;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author samue
 */
public class Page2 extends javax.swing.JPanel {

    /**
     * Creates new form Page2
     */
    public Page2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuBottonPage1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(708, 257));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(730, 270));

        MenuBottonPage1.setBackground(new java.awt.Color(204, 204, 255));
        MenuBottonPage1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        MenuBottonPage1.setForeground(new java.awt.Color(102, 102, 102));
        MenuBottonPage1.setText("Menu");
        MenuBottonPage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBottonPage1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("See");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(177, 177, 177)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MenuBottonPage1))
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuBottonPage1)
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void MenuBottonPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBottonPage1ActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();

        Inicio in = new Inicio();
        in.setVisible(true);
    }//GEN-LAST:event_MenuBottonPage1ActionPerformed

   
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{
         //CREAR UN LECTOR DE ARCHIVOS PARA articulos.txt
         FileReader fileReader = new FileReader("articulos.txt");
         BufferedReader bufferedReader = new BufferedReader(fileReader);
         
         StringBuilder mensaje = new StringBuilder();
         String line;
         int cantidadDeProductosDeLArrayOTXT = 0;
         int lineaProcesada = 0;
         while((line = bufferedReader.readLine()) !=null){
             lineaProcesada++;
             //ANALIZA CADA LINEA Y SEPARA LA INFORMACION DESEADA
             String [] parts = line.split(", ");
             if(parts.length==4){//AGREGA Y ASUME QUE CADA LINEA TIENE 4 CAMPOS
                 cantidadDeProductosDeLArrayOTXT++;
                 String nombre = parts[0].substring(8);//REMUEVE EL PRECIO AL INICIO
                 int precio = Integer.parseInt(parts[1].substring(8));//REMUEVE EL PRECIO AL INICIO
                 int cantidad = Integer.parseInt(parts[2].substring(10));//REMUEVE ASI MISMO AL INICIO TAMBIEN
                 int indice = Integer.parseInt(parts[3].substring(8));//REMUEVE AL INICIO
                 
                 mensaje.append("Index In The Array: ").append(lineaProcesada)
                         .append(" , Article: ").append(nombre)
                         .append(" , Price: ").append(precio)
                         .append(" , Amount Of The Product: ").append(cantidad)
                         .append(" , Index Independent: ").append(indice)
                         .append("\n");
             }
         }
         bufferedReader.close();
         //AGERGA LA CANTIDAD DE PRODCUTO AL MENSAJE
         mensaje.insert(0, "Amount Of Elements: " + cantidadDeProductosDeLArrayOTXT + "\n\n");
         
         //MOSTRAR LA INFORMACION AL RESPECTO DEL INVENTARIO EN UN CUADRO DE DIALOGO
         JOptionPane.showMessageDialog(null, mensaje.toString(), "Inventory: ", JOptionPane.INFORMATION_MESSAGE);
     }catch(IOException e){
         e.printStackTrace();
         JOptionPane.showMessageDialog(this, "ERROR");
     }
     
     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuBottonPage1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
