/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Windows;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author samue
 */
public class Page5 extends javax.swing.JPanel {

    /**
     * Creates new form Page5
     */
    public Page5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MenuBottonPage1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(730, 270));

        MenuBottonPage1.setBackground(new java.awt.Color(204, 204, 255));
        MenuBottonPage1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        MenuBottonPage1.setForeground(new java.awt.Color(102, 102, 102));
        MenuBottonPage1.setText("Menu");
        MenuBottonPage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBottonPage1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Eliminate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Write The Index Of The Article To Eliminate:");

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trash.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuBottonPage1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel2)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MenuBottonPage1)
                .addGap(139, 139, 139))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void MenuBottonPage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBottonPage1ActionPerformed
        SwingUtilities.getWindowAncestor(this).dispose();

        Inicio in = new Inicio();
        in.setVisible(true);
    }//GEN-LAST:event_MenuBottonPage1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String input = jTextField1.getText().trim();

    if (input.isEmpty()) 
    {
        JOptionPane.showMessageDialog(this, "The Space Is Required");
    } 
    else 
    {
        try 
        {
            int indexToDelete = Integer.parseInt(input);
            
            if (indexToDelete < 1) 
            {
                JOptionPane.showMessageDialog(this, "Invalid Index. Please Enter A Valid Index.");
            } 
            
            else 
            {
                int confirmation = JOptionPane.showConfirmDialog(this, "Are You Sure You Want To Delete The Product At Index " + indexToDelete + "?", "Confirmation", JOptionPane.YES_NO_OPTION);
                if (confirmation == JOptionPane.YES_OPTION) 
                {
                    eliminarProducto(indexToDelete);
                    jTextField1.setText(""); // Limpiar el campo de texto después de eliminar el producto
                }
            }
        } 
        
        catch (NumberFormatException e) 
        {
            JOptionPane.showMessageDialog(this, "The Input Must Be A Valid Number.");
        }
    }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    
private void eliminarProducto(int indexToDelete) {
    try {
        File inputFile = new File("articulos.txt");
        File tempFile = new File("temp_articulos.txt");

        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile));

        String currentLine;
        int currentLineIndex = 0;
        boolean found = false;

        while ((currentLine = reader.readLine()) != null) 
        {
            currentLineIndex++;
            
            if (currentLine.contains("Índice: " + indexToDelete)) 
            {
                found = true;
                continue; // Skip this line
            }
            writer.write(currentLine + System.getProperty("line.separator"));
        }

        writer.close();
        reader.close();

        if (!found) 
        {
            JOptionPane.showMessageDialog(this, "Product at Index " + indexToDelete + " Not Found.");
        } 
        
        else 
        {
            if (inputFile.delete()) 
            
            {
                if (!tempFile.renameTo(inputFile)) 
                {
                    JOptionPane.showMessageDialog(this, "Error Renaming File");
                }
            } 
            else 
            {
                JOptionPane.showMessageDialog(this, "Error Deleting File");
            }

            DatosProductos.cantidadDeProductosDelArrayOTXT--; // Actualizar la cantidad de productos
            JOptionPane.showMessageDialog(this, "Product at Index " + indexToDelete + " Deleted Successfully.");
        }
    } catch (Exception e) 
    {
        JOptionPane.showMessageDialog(this, "Error Deleting Product: " + e.getMessage());
    }
}

public class DatosProductos {
    public static int cantidadDeProductosDelArrayOTXT = 0;
}
    
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuBottonPage1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
