/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Windows;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
/**
 *
 * @author samue
 */
public class Start extends javax.swing.JFrame {

    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/book.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExit = new javax.swing.JButton();
        jLabelIcono1 = new javax.swing.JLabel();
        jLabel1User = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        jTextFieldUsertext1 = new javax.swing.JTextField();
        jPasswordStartField1 = new javax.swing.JPasswordField();
        jButton1StartSesion = new javax.swing.JButton();
        JLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExit.setBackground(new java.awt.Color(204, 204, 255));
        jButtonExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(102, 102, 102));
        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 60, 20));

        jLabelIcono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.jpg"))); // NOI18N
        getContentPane().add(jLabelIcono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 120, 120));

        jLabel1User.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1User.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1User.setText("User :");
        getContentPane().add(jLabel1User, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 60, 30));

        Password.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password :");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 30));

        jTextFieldUsertext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsertext1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUsertext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 150, 30));
        getContentPane().add(jPasswordStartField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 150, 30));

        jButton1StartSesion.setBackground(new java.awt.Color(204, 204, 255));
        jButton1StartSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1StartSesion.setForeground(new java.awt.Color(102, 102, 102));
        jButton1StartSesion.setText("Log in");
        jButton1StartSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1StartSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1StartSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 80, 30));

        JLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Inteface.jpg"))); // NOI18N
        getContentPane().add(JLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 329, 491));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButton1StartSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1StartSesionActionPerformed
        String usuario = "admin";
        String contraseña = "123";
        
        String Pass= new String(jPasswordStartField1.getPassword());
        
        if(jTextFieldUsertext1.getText().equals(usuario)&& Pass.equals(contraseña))
        {
            Inicio GN = new Inicio();
            GN.setVisible(true);
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Password Or User Is Incorrect");
        }
    }//GEN-LAST:event_jButton1StartSesionActionPerformed

    private void jTextFieldUsertext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsertext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsertext1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelFondo;
    private javax.swing.JLabel Password;
    private javax.swing.JButton jButton1StartSesion;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1User;
    private javax.swing.JLabel jLabelIcono1;
    private javax.swing.JPasswordField jPasswordStartField1;
    private javax.swing.JTextField jTextFieldUsertext1;
    // End of variables declaration//GEN-END:variables
}
